Repository Co-Studo/cos-ui, pull requests merged in 2022-12, with the labels that each got.

#11 [Hemdi] FlexBox gap rem 단위, 속성 추가
  packages/react/src/components/FlexBox/index.tsx
  packages/react/src/styles/spacing.ts
Labels: ✨ Feature

#7 [Dony] Table 컴포넌트 구현
  packages/playground-react/constants/icons.tsx
  packages/playground-react/constants/mock.ts
  packages/playground-react/helpers/table/index.ts
  packages/playground-react/pages/table/basic-table.tsx
  packages/playground-react/pages/table/column-table.tsx
  packages/playground-react/pages/table/row-table.tsx
  packages/playground-react/tsconfig.path.json
  packages/primitives/src/components/Table/BasicTable.tsx
  packages/primitives/src/components/Table/Cell/index.tsx
  packages/primitives/src/components/Table/ColumnTable.tsx
  packages/primitives/src/components/Table/RowTable.tsx
  packages/primitives/src/components/Table/index.tsx
  packages/primitives/src/index.ts
  packages/primitives/src/styles/commonStyles.ts
  packages/primitives/tsconfig.path.json
  packages/react/src/components/Table/BasicTable.tsx
  packages/react/src/components/Table/ColumnTable.tsx
  packages/react/src/components/Table/RowTable.tsx
  packages/react/src/components/Table/index.tsx
  packages/react/src/index.ts
  packages/react/src/styles/GlobalStyle.ts
Labels: ✨ Feature

#15 [Jamie] Text, Tab, AvatarGroup 수정
  packages/primitives/src/components/Tab/index.tsx
  packages/react/src/components/AvatarGroup/index.tsx
  packages/react/src/components/Tab/basicTab.tsx
  packages/react/src/components/Tab/borderTab.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/styles/fonts.ts
Labels: ✨ Feature

#16 [Park] Husky 도입 및 eslint, tsconfig 설정 변경
  .eslintignore
  .eslintrc.js
  .husky/pre-commit
  lint-staged.config.js
  package.json
  packages/playground-react/.eslintignore
  packages/playground-react/.eslintrc.js
  packages/playground-react/tsconfig.json
  packages/playground-react/tsconfig.path.json
  packages/primitives/.eslintignore
  packages/primitives/tsconfig.eslint.json
  packages/primitives/tsconfig.json
  packages/primitives/tsconfig.path.json
  packages/react/.eslintignore
  packages/react/.eslintrc.js
  packages/react/src/components/Button/index.tsx
  packages/react/tsconfig.eslint.json
  packages/react/tsconfig.json
  packages/react/tsconfig.path.json
  tsconfig.json
  yarn.lock
Labels: ⚙️ env

#19 [Dony] Palette 수정
  packages/playground-react/pages/_app.tsx
  packages/playground-react/pages/button/button.tsx
  packages/playground-react/pages/index.tsx
  packages/primitives/src/components/Dropdown/index.tsx
  packages/react/src/components/AvatarGroup/index.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/Dropdown/index.tsx
  packages/react/src/components/FlexBox/index.tsx
  packages/react/src/components/Form/index.tsx
  packages/react/src/components/Paper/index.tsx
  packages/react/src/components/Tab/basicTab.tsx
  packages/react/src/components/Tab/borderTab.tsx
  packages/react/src/components/Table/BasicTable.tsx
  packages/react/src/components/Table/ColumnTable.tsx
  packages/react/src/components/Table/RowTable.tsx
  packages/react/src/components/Text/index.tsx
  packages/react/src/index.ts
  packages/react/src/styled.d.ts
  packages/react/src/styles/GlobalStyle.ts
  packages/react/src/styles/colors.ts
  packages/react/src/styles/theme.ts
Labels: ♻️ Refactoring, 💄 Style

#18 [Jamie] Loading Spinner 컴포넌트 생성 및 자잘한 수정
  packages/playground-react/constants/avatar.ts
  packages/playground-react/pages/avatar/avatar.tsx
  packages/playground-react/pages/loading-spinner/loading-spinner.tsx
  packages/react/src/components/AvatarGroup/index.tsx
  packages/react/src/components/Button/index.tsx
  packages/react/src/components/LoadingSpinner/index.tsx
  packages/react/src/components/Tab/basicTab.tsx
  packages/react/src/index.ts
Labels: ✨ Feature

#21 [Park] exclude unnecessary files on publish
  packages/primitives/package.json
  packages/react/package.json
Labels: ⚙️ env

#23 [Park] Slide - Check children is undefined
  packages/primitives/src/components/Slider/Slider.tsx
Labels: 🐛 Bug

#26 [Park] FlexBox forwardRef 적용
  packages/playground-react/pages/flexBox/flexBox.tsx
  packages/react/src/components/FlexBox/flexBox.md
  packages/react/src/components/FlexBox/flexBox.tsx
  packages/react/src/components/FlexBox/index.tsx
  packages/react/src/index.ts
  packages/react/src/styles/GlobalStyle.ts
Labels: ✨ Feature

#30 [Park] AvatarGroup key bug fix & Avatar SX 제한 및 개선
  packages/playground-react/pages/avatar/avatar.tsx
  packages/react/src/components/Avatar/avatar.md
  packages/react/src/components/Avatar/avatar.tsx
  packages/react/src/components/Avatar/index.tsx
  packages/react/src/components/AvatarGroup/avatarGroup.md
  packages/react/src/components/AvatarGroup/avatarGroup.tsx
  packages/react/src/components/AvatarGroup/index.tsx
  packages/react/src/index.ts
  packages/react/src/styles/fonts.ts
Labels: 🐛 Bug, ✨ Feature
